apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomizeconfig.yaml

resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
  - persistentvolumeclaim.yaml

configMapGenerator:
  - name: config
    envs:
    - config.env

vars:
- name: ROUTE_SERVICE
  objref:
    kind: Service
    name: wordpress
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name