kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-content
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
