apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

# define a common label for your app!
commonLabels:
  app.kubernetes.io/part-of: testpress
# set a name prefix
namePrefix: testpress-

# add a hostname for a route. If not specified, it will be generated
patches:
  - patch: |-
      - op: add
        path: /spec/host
        value: testpress.imhere.net
    target:
      kind: Route
      name: wordpress
# optional: enable openshift-acme on the route
  - patch: |-
      - op: add
        path: /metadata/annotations
        value: 
          kubernetes.io/tls-acme: 'true'
    target:
      kind: Route
      name: wordpress
# optional: add label to pod
  - patch: |-
      - op: add
        path: /spec/template/metadata/labels
        value:
          pflaeging.net/expose: route
    target:
      kind: Deployment
      name: wordpress

# patch storageclasses
patchesStrategicMerge:
  - |-
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: wp-content
    spec:
      storageClassName: netapp-trident-brz-delete
  - |-
    kind: StatefulSet
    apiVersion: apps/v1
    metadata:
      name: mariadb
    spec:
      volumeClaimTemplates:
      - metadata:
          name: mariadb
        spec:
          storageClassName: netapp-trident-brz-delete
          volumeMode: Filesystem
          accessModes: 
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Mi

# replace default images with local versions
images:
- name: docker.io/centos/mariadb-103-centos7
  newName: image-registry.openshift-image-registry.svc:5000/sb/mariadb-103-centos7
  newTag: latest
- name: quay.io/pflaeging/wordpress-okd
  newName: image-registry.openshift-image-registry.svc:5000/brz-ws-paas/wordpress-container
  newTag: latest