kind: Service
apiVersion: v1
metadata:
  name: mariadb
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
  sessionAffinity: None