kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mariadb
spec:
  replicas: 1
  serviceName: mariadb
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: docker.io/centos/mariadb-103-centos7:latest
          envFrom:
            - secretRef:
                name: database
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - metadata:
        name: mariadb
        labels:
          app: mariadb
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rook-ceph-block
        volumeMode: Filesystem
        resources:
          requests:
            storage: 200Mi
