kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wordpress-container
  labels:
    app: wordpress-container
    app.kubernetes.io/component: wordpress-container
    app.kubernetes.io/instance: wordpress-container
    app.kubernetes.io/part-of: wordpress
spec:
  nodeSelector: null
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  output:
    to:
      kind: ImageStreamTag
      name: 'wordpress-container:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/jaysonzhao/wordpress-okd.git'
      ref: master
    contextDir: /wordpress-container
    
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: wordpress-container-generic-webhook-secret
    - type: GitLab
      gitlab:
        secretReference:
          name: wordpress-container-gitlab-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
