kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workshop-wp-content
  labels:
    app: wordpress
    cp.cna.at/instance: workshop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: netapp-trident-prz-delete
  volumeMode: Filesystem
