kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workshop-wp-content
  labels:
    app: wordpress
    cp.cna.at/instance: workshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: ocs-storagecluster-ceph-mirror
  volumeMode: Filesystem
