kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: workshop-mariadb
spec:
  replicas: 1
  serviceName: workshop-mariadb
  selector:
    matchLabels:
      app: workshop-mariadb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workshop-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.3-el8
          envFrom:
            - secretRef:
                name: workshop-database
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: workshop-mariadb
              mountPath: /var/lib/mysql
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - metadata:
        name: workshop-mariadb
        labels:
          app: mariadb
          cp.cna.at/instance: workshop
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: netapp-trident-prz-delete
        volumeMode: Filesystem
        resources:
          requests:
            storage: 200Mi
